// automatically generated by the FlatBuffers compiler, do not modify

package passxtended.protos;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class files extends Table {
  public static files getRootAsfiles(ByteBuffer _bb) { return getRootAsfiles(_bb, new files()); }
  public static files getRootAsfiles(ByteBuffer _bb, files obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public files __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public file allFiles(int j) { return allFiles(new file(), j); }
  public file allFiles(file obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int allFilesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createfiles(FlatBufferBuilder builder,
      int all_filesOffset) {
    builder.startObject(1);
    files.addAllFiles(builder, all_filesOffset);
    return files.endfiles(builder);
  }

  public static void startfiles(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addAllFiles(FlatBufferBuilder builder, int allFilesOffset) { builder.addOffset(0, allFilesOffset, 0); }
  public static int createAllFilesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAllFilesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endfiles(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishfilesBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedfilesBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

